### ISSUE TITLE
Auth Support

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/MQClient#20]
Add auth token support to all backends.

Something like:
```
from pulsar import Client, AuthenticationToken

client = Client('pulsar://broker.example.com:6650/', authentication=AuthenticationToken('eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb2UifQ.ipevRNuRP6HflG8cFKnmUPtypruRC4fb1DWtoLL62SY'))
```

From @dsschult:
> even something like passing through any extra kwargs to the backend, and then it can decide if they are valid.  in case some of them take different parameters to set up advanced features
> that way we don't have to try figuring out how to make each backend's auth look the same, just provide docs for each one

**Comment by dsschult** [comment]
At least in the pulsar case, I assume the `Pulsar.__init__()` function can do the translation step between jwt and `AuthenticationToken`, so the user doesn't have to load the pulsar library themselves.
