### ISSUE TITLE
Make Async

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/MQClient#27]
The NATS API supports async, but we're ignoring it currently with `run_until_complete()` calls. Let's support that functionality in the backend interface to get the performance gains. This would also mean making _all_ the backend implementations support async, at least at face value, for consistency's sake. ~This _could_ mean placing dummy async calls (hopefully something better than `asyncio.sleep()`) until the backend APIs catch up to NATS.~

**Comment by dsschult** [comment]
What would the `sleep()` calls be for?  I assume you'd just call the existing backend APIs with non-async blocking calls until they were upgraded.

**Comment by ric-evans** [comment]
I've never declared a function `async` without containing any actual `await` calls. Can this be done?

**Comment by dsschult** [comment]
Sure, no problem.
