### ISSUE TITLE
Better Nack Usage

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/MQClient#34]
The send methods are context managers that auto-ack/nack. However, since there is no persisted `sub` instance for the `Queue` class, a user-friendly manual method of nacking is absent.

The trivial solution would be to have the user raise any `Exception` from within the context. This would work fine, but the intention is not obvious.

I propose two solutions:
1. a publicly available exception `CancelMessage` which can be raised
2. a `Queue` (or `MessageAsyncGeneratorContext`) method that raises the `CancelMessage` exception

**Comment by dsschult** [comment]
I suppose you could put that method on `MessageAsyncGeneratorContext`.
